### ISSUE TITLE
GetDrivesInfo Access is denied

### ISSUE THREAD

**Issue by codemonster33** [Yeeterboi4/driveutil#1]
## GetDrivesInfo Doesn't Work For Main C:/ Drive

GetDrivesInfo in driveutil doesn't work for main C drive, when trying to get drive info of
C it will tell you that Access is denied. I belive this is an issue with fsutil as when running the command
founded in the GetDrivesInfo command ```fsutil fsinfo volumeinfo C:``` it will return this

<img width="279" alt="Annotation 2022-04-15 201603" src="https://user-images.githubusercontent.com/79758393/163601482-2a54c6b5-884e-4c7d-90b8-72caab0ce9dc.png">

While this works for other drives and ROS doesn't need this feature i still think its important if this package
is marketed as just driveutil.

**Comment by ObjRand** [comment]
For Hard Drives, Use Admin Rights!

**Comment by ObjRand** [comment]
It Uses Admin

**Comment by ObjRand** [comment]
Ok, Bozo?
